### ISSUE TITLE
Heat creep related jamming with ceramic heat break

### ISSUE THREAD

**Issue by TheRealDeathsneeze** [TheRealDeathsneeze/Deconstruder#4]
As of the time of this writing, I have experienced multiple instances where the ceramic heat break of the NF Crazy has not had adequate thermal performance to allow for adequate performance in printers with elevated chamber temperatures. I have experienced these issues at temperatures above 80C for ABS, and 105C for 3DXTech ezPC. 

These issues have not occurred with ABS at 75C chamber, or 95-100C chamber with ezPC. Thermal performance has been more than adequate at reduced chamber temperatures, and it is likely that only users that are operating at elevated temperatures will experience this issue. 

For now, it is suggested to avoid using the ceramic heat break and instead use the older bimetal copper/stainless heatbreak or the one peice titanium unit.

**Comment by TheRealDeathsneeze** [comment]
One possible solution will be to adjust the rear portion of the fan net to allow more area for the exhaust from the hot end fan, which may also assist in wiring management with the hot end and thermistor wires. An updated fan net will be developed, which should also be easier to install as well

**Comment by HumbleDeer** [comment]
On what hot end is this exactly? Just a stock setup of an NF Crazy? I may
order parts necessary to measure more closely with a thermocouple. I've got
time to kill, and probably printer parts too.
